# config path: '~/.config/alacritty/alacritty.toml'
import = [
	"~/.config/alacritty/themes/dracula.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[shell]
    args    = ["-l", "-c", "tmux attach || tmux"]
    program = "/bin/zsh"

[font]
size = 12.0

    # [font.bold]
    #     family = "FiraCode Nerd Font"
    #     style  = "Bold"
    # [font.bold_italic]
    #     family = "FiraCode Nerd Font"
    #     style  = "Bold Italic"
    # [font.italic]
    #     family = "FiraCode Nerd Font"
    #     style  = "Italic"

    [font.glyph_offset]
        x = 0
        y = 0

    [font.normal]
        family = "Fantasque Sans Mono"
        style  = "Regular"

    [font.bold]
        family = "Fantasque Sans Mono"

    [font.italic]
        family = "Fantasque Sans Mono"

    [font.offset]
        x = 0
        y = 0

[window]
	padding.x = 8
	padding.y = 4
	# dynamic_padding = true
	decorations = "none"
	startup_mode = "Maximized" 
	opacity = 0.85

[selection]
    save_to_clipboard     = true
    semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[scrolling]
    history    = 100000
    multiplier = 4

[mouse]
hide_when_typing = true 


[cursor]
	unfocused_hollow = true
	[cursor.style]
		shape = "Beam"
		blinking = "Always"
	[cursor.vi_mode_style]
		shape = "Beam"
		blinking = "Off"
	[colors.cursor]
	text = "#002b36"
